config/routes.rb
CincopalabritasCom::Application.routes.draw do

  get "word_set/destroy"

  get "home/index"

  devise_for :users # , :controllers => { :registrations => 'registrations' }

  devise_for :users do
    get "/entrar" => "devise/sessions#new"
  end
  devise_scope :user do
    get "/cerrar_session" => "devise/sessions#destroy"
  end
  devise_scope :user do
    get "/registrate" => "devise/registrations#new"
  end

  root :to => "home#index"

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  
    
  resources :user do
    resources :word_sets
    member do
      get :dashboard
      get :find_friends
      get :settings
    end

    collection do
      get :validate_form_data
      post :share_on_wall
    end
    
  end

  match 'dashboard' => 'user#dashboard', :as => 'user_root'
  

  match '/:username' => 'user#show', :as => :show_user #, :constraints => { :username => /(?!.*?admin).*/ }

end

app/views/shared/_error_messages.haml
-if target.errors.any?
#errorExplanation
  %ul
    -target.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_footer.html.haml
\©2011 5palabritas.com. Creado por Fabian Dittrich

app/views/shared/_header.html.haml
#negative_margin_header
  #small_logo=image_tag "logo_small.png", :class => "fixpng", :size => '141x25'
  #loginout
    #text_links
      -if user_signed_in?
        !=t(".hola_username", :link => link_to(current_user.get_username, user_root_path))+"&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;"

        !=link_to(t(".your_public_page"), show_user_path(current_user.get_username))
        &nbsp;

      -if user_signed_in?
        \|
        &nbsp;
        = link_to(t(".settings"), edit_user_path(current_user.id))

      -else
        =link_to t(".login"), new_user_session_path, :style => "margin-right: 10px"
        =link_to(image_tag("facebook_login_small.png", :size => '64x22'), "/auth/facebook", :class => "sth_with_facebook")
        

    -if user_signed_in?
      =link_to_function image_tag("fb_invite_friends.png", :size => '133x22'), "FB.ui({method: 'apprequests', message: '¡Hola, Tienes que conocer esa pagina!.', data: 'tracking information for the user'});", :style => "margin-left: 10px"

      = link_to(image_tag("btn_logout.png"), destroy_user_session_path, :style => "float: left;")
      

    -if !user_signed_in?
      =link_to image_tag("btn_registrate.png", :size => '75x22'), new_user_registration_path, :style => "float: left;"