config/routes.rb
CincopalabritasCom::Application.routes.draw do

  get "word_set/destroy"

  get "home/index"

  devise_for :users # , :controllers => { :registrations => 'registrations' }

  devise_for :users do
    get "/entrar" => "devise/sessions#new"
  end
  devise_scope :user do
    get "/cerrar_session" => "devise/sessions#destroy"
  end
  devise_scope :user do
    get "/registrate" => "devise/registrations#new"
  end

  root :to => "home#index"

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  
    
  resources :user do
    resources :word_sets
    member do
      get :dashboard
      get :find_friends
      get :settings
    end

    collection do
      get :validate_form_data
      post :share_on_wall
    end
    
  end

  match 'dashboard' => 'user#dashboard', :as => 'user_root'
  

  match '/:username' => 'user#show', :as => :show_user #, :constraints => { :username => /(?!.*?admin).*/ }

end

app/models/word.rb
class Word < ActiveRecord::Base
  # acts_as_paranoid
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < Admin::ResourcesController
end

app/views/words/_word_set.haml
.word_set
  =render_avatar(word_set.sender, "thumb")
  .words
    %p.who!="<b>#{set_sender_name(word_set)}</b> dijo que eres:"
    %p!=set_words(word_set)
    %p.time_ago="hace " + time_ago_in_words(word_set.created_at)
    
  .actions
    = link_to(image_tag("btn_reply.jpg"), "#", :class => "btn_leave_reply") if current_user
    = button_to("", user_word_set_path(@user, word_set), :confirm => "¿Estas seguro?", :method => :delete) if current_user && current_user == word_set.receiver
  .clear
  
  .word_set_comments{:class => (word_set.comments.any?  ? nil : "hidden_content")}
    =render :partial => "word_set/comment", :collection => word_set.comments, :locals => {:word_set => word_set}

  .word_set_comment_form.hidden_content
    -if current_user
      -form_for [@user, word_set], :html => {:id => "word_set_reply_form"}, :method => :post do |f|
        =text_area_tag "word_set[comment]", nil, :class => "reply_text_field"
        =submit_tag "Enviar comentario" , :id => "submit_word_form"
  
.divider{:class => ((word_set_counter+1) == total_count ? "last" : nil)} &nbsp;

app/views/words/_word_set_for_show.haml
!="#{set_sender_name(set)} dijo que eres #{set_words(set)}"
%br